In [ ]:
from ase.io import read
from ase.visualize import view
import nglview as nv
from IPython.display import display
from ipywidgets import Layout
from fairchem.core.datasets.ase_datasets import AseDBDataset
from src_v2.distill_datasets import LmdbHessianIndexDataset
dataset_path = '/data/ishan-amin/OMOL/electrolytes_application/aselmdb_data/NAPF6/s1p1/train'
dataset = AseDBDataset({
    "src": dataset_path,
})
idxs_dataset = LmdbHessianIndexDataset(folder_path='/data/ishan-amin/OMOL/electrolytes_application/labels/NAPF6/s1p1/force_jacobians')
idxs = idxs_dataset[0]
idxs = idxs.reshape(60, 2)
idxs = idxs[::3, 0].numpy()
atoms = dataset.get_atoms(0)
# Create nglview widget with larger size
viewer = nv.show_ase(atoms)
viewer.layout = Layout(width='800px', height='1200px')  # Set display size
# # Clear default representations to avoid overlap
viewer.clear()

comma


viewer.add_representation('ball+stick', selection=f'@{comma_separated_string}', radius=0.2, bondRadius=0.01)
viewer.add_representation('ball+stick', selection='*', radius=0.2, bondRadius=0.01, opacity= 0.1)

# # Display the viewer
# display(viewer)

Total entries across all LMDB files jacs: 2460
[1703 2008 2045 2078  617 1148 2104  873 1378 2026  828 1602  869 2039
 2047 2100 1442    6 2094  313]


NGLWidget(layout=Layout(height='1200px', width='800px'))

In [5]:
# Extract energies, forces, and stress from the 0th structure
atoms0 = atoms_list[0]
energy0 = atoms0.get_potential_energy()
forces0 = atoms0.get_forces()
stress0 = atoms0.get_stress()
print(atoms0.calc.results)

print("Energy (0th structure):", energy0)
print("Forces (0th structure):", forces0)
print("Stress (0th structure):", stress0)

{'forces': array([[ 0.50138307, -0.3143748 ,  0.18381397],
       [-0.24248847,  0.0123096 , -1.06037176],
       [ 0.26403108, -1.2291187 ,  0.30364525],
       ...,
       [-3.21713376, -0.91773218, -0.19000071],
       [ 0.30188063, -3.49947357,  0.90000278],
       [ 0.34586483,  0.02238585,  1.76250982]]), 'energy': -10871.834495908546, 'stress': array([ 0.00014651, -0.00080037, -0.00146316, -0.00168616,  0.0004206 ,
       -0.00031137])}
Energy (0th structure): -10871.834495908546
Forces (0th structure): [[ 0.50138307 -0.3143748   0.18381397]
 [-0.24248847  0.0123096  -1.06037176]
 [ 0.26403108 -1.2291187   0.30364525]
 ...
 [-3.21713376 -0.91773218 -0.19000071]
 [ 0.30188063 -3.49947357  0.90000278]
 [ 0.34586483  0.02238585  1.76250982]]
Stress (0th structure): [ 0.00014651 -0.00080037 -0.00146316 -0.00168616  0.0004206  -0.00031137]
