In [2]:
import sys
sys.path.append("../..")
sys.path.append("..")
import torch
from src_v2.distill_datasets import LmdbDataset, LmdbHessianIndexDataset
import matplotlib.pyplot as plt
import lmdb
import pickle
from tqdm import tqdm
from fairchem.core.datasets import AseDBDataset
import numpy as np
from torch.utils.data import Subset
from IPython.display import Image, display
import ase

/pscratch/sd/y/yuejian/envs/fairchemV2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# load dataset
dataset_path = "/global/homes/y/yuejian/project/MLFF-distill/m5024/distillation_project/data/lmdb_for_distillation/all_salt_all_concentration_first_50ps/train"
a2g_args = {  
    # "molecule_cell_size": 120.0,
    "r_energy": True,
    "r_forces": True,
    # "r_stress": True,
    "r_data_keys": [ 'spin','charge', "data_id"],
    # 'sid': 'data_id',
}
# select_args ={ "data_id":"ani2x"}
# select_args ={"selection": [("charge", "=", -1)] }
# select_args = {
#     "filter": lambda row: row._data.get("data_id") == "orbnet_denali"
# }
dataset = AseDBDataset({
    "src": dataset_path,
    "a2g_args": a2g_args,
    # "select_args": select_args,
})

# # How to know the length of the dataset:
print("Length of dataset:", len(dataset))


Length of dataset: 72


In [4]:
# Load metadata.npz containing natoms array (number of atoms per entry)
metadata_path = "/global/homes/y/yuejian/project/MLFF-distill/m5024/distillation_project/data/lmdb_for_distillation/all_salt_all_concentration_first_50ps/train/metadata.npz"
metadata = np.load(metadata_path)
if "natoms" in metadata:
    natoms = metadata["natoms"]
    print("Loaded natoms from metadata.npz. Shape:", natoms.shape)
    print("First 10 number of atoms entries:", natoms[:10])
else:
    print("No 'natoms' key found in metadata.npz")

Loaded natoms from metadata.npz. Shape: (72,)
First 10 number of atoms entries: [2072 2072 2072 2072 2072 2072 2072 2072 2072 2072]


In [18]:
src = "/global/homes/y/yuejian/project/MLFF-distill/m5024/distillation_project/other/ablate_dense_sample/sample_10_lipf6/force_jacobians"
fd_dataset = LmdbHessianIndexDataset(
    folder_path=src,
)
for i in range(len(fd_dataset)):
    print(i)
    print(fd_dataset[i])

{'psize': 4096, 'depth': 2, 'branch_pages': 1, 'leaf_pages': 18, 'overflow_pages': 338400, 'entries': 1800}
Total entries across all LMDB files jacs: 900
0


Exception: Data not found for index 0 in LMDB file.

In [12]:
src = "/global/homes/y/yuejian/project/MLFF-distill/yuejian/electrolytes/merged_shards/label/force_jacobians"
# target = "/home/yuejian/project/MLFF-distill/OMOL/TOY/labels/ligand_pocket_1000_esen_md_fd_dt_0_0001/train_forces/data.lmdb"
fd_dataset = LmdbDataset(
    folder_path=src,
    div_2=True
)
for i in range(len(fd_dataset)):
    print(i)
    print(fd_dataset[i])

{'psize': 4096, 'depth': 1, 'branch_pages': 0, 'leaf_pages': 1, 'overflow_pages': 1380, 'entries': 60}
Total entries across all LMDB files jacs: 30
0
tensor([ 2.5445e-04, -3.3927e-04, -4.2409e-05,  ...,  7.6336e-04,
         1.1874e-03, -1.6963e-03])
1
tensor([-0.0003,  0.0003, -0.0008,  ..., -0.0365, -0.0009,  0.0419])
2
tensor([-0.0006, -0.0011, -0.0007,  ...,  0.0013, -0.0037, -0.0066])
3
tensor([-0.0003, -0.0006, -0.0003,  ..., -0.0031,  0.0005, -0.0153])
4
tensor([ 0.0001,  0.0003, -0.0002,  ..., -0.0478,  0.0149, -0.0228])
5
tensor([-0.0002,  0.0008,  0.0000,  ..., -0.0020, -0.0007,  0.0003])
6
tensor([-1.6963e-04, -8.4817e-05,  8.4817e-05,  ..., -2.0399e-02,
        -2.6930e-03,  1.3104e-02])
7
tensor([-2.3325e-04, -1.6963e-04,  6.7854e-04,  ..., -1.6963e-04,
        -8.4817e-05, -1.0178e-03])
8
tensor([ 0.0003, -0.0002,  0.0000,  ..., -0.0001,  0.0008, -0.0005])
9
tensor([-0.0002,  0.0003,  0.0002,  ..., -0.0031, -0.0087, -0.0069])
10
tensor([ 2.5445e-04, -3.3927e-04, -4.2409e-

In [9]:
for i in range(len(fd_dataset)):
    print(i)
    print(fd_dataset[i])
    break

0
tensor([ 2.5445e-04, -3.3927e-04, -4.2409e-05,  ...,  7.6336e-04,
         1.1874e-03, -1.6963e-03])


In [14]:
src = "/global/homes/y/yuejian/project/MLFF-distill/yuejian/electrolytes/all_shards/toy_dir2/label/force_jacobians"
# target = "/home/yuejian/project/MLFF-distill/OMOL/TOY/labels/ligand_pocket_1000_esen_md_fd_dt_0_0001/train_forces/data.lmdb"
fd_dataset = LmdbDataset(
    folder_path=src,
    div_2=True
)

Total entries across all LMDB files jacs: 10


In [5]:
# load dataset
dataset_path = "/global/homes/y/yuejian/project/MLFF-distill/yuejian/electrolyte_application/unformal_ablation/ablate_dense_sample/naotf_lmdbs_323K/unequilibrated/train"
a2g_args = {  
    "molecule_cell_size": 120.0,
    "r_energy": True,
    "r_forces": True,
    # "r_stress": True,
    "r_data_keys": [ 'spin','charge', "data_id"],
    # 'sid': 'data_id',
}
# select_args ={ "data_id":"ani2x"}
# select_args ={"selection": [("charge", "=", -1)] }
select_args = {
    "filter": lambda row: row._data.get("data_id") == "orbnet_denali"
}
dataset = AseDBDataset({
    "src": dataset_path,
    "a2g_args": a2g_args,
    # "select_args": select_args,
})

# # How to know the length of the dataset:
print("Length of dataset:", len(dataset))


Length of dataset: 3600


In [4]:
print("Length of dataset:", len(dataset))

Length of dataset: 900
