In [2]:
from fairchem.core.datasets import AseDBDataset
from tqdm import tqdm
import numpy as np
import torch
from torch.utils.data import Subset
from IPython.display import Image, display
import ase

/home/ishan-amin/miniconda3/envs/fairchemV2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
dst_path = "../tester_data/solvated_train.aselmdb"
dst_db = ase.db.connect(dst_path, use_lock_file=False)

In [23]:
# load dataset
# dataset_path = "/data/yuejian/OMol_Whole/val"
dataset_path = "../tester_data/train"
a2g_args = {  
    # "molecule_cell_size": 120.0,
    "r_energy": True,
    "r_forces": True,
    # "r_stress": True,
    # "r_data_keys": [ 'spin','charge', "data_id"],
    # 'sid': 'data_id',
}
# select_args ={ "data_id":"ani2x"}
# select_args ={"selection": [("charge", "=", -1)] }
select_args = {
    "filter": lambda row: row._data.get("data_id") == "orbnet_denali"
}
dataset = AseDBDataset({
                        "src": dataset_path,
                        "a2g_args": a2g_args,
                        # "select_args": select_args,
                        })

In [31]:
a = dataset[0]
print(a.energy)
print(a.forces)
print(a.keys())

tensor([-59839.5547])
tensor([[ 0.1972, -0.1349,  0.0616],
        [-0.2270,  1.1344,  0.1714],
        [ 1.7660,  0.9128,  0.2354],
        [ 0.3723, -1.3173, -0.3917],
        [ 0.3054,  0.7133, -0.3659],
        [ 2.3021,  1.6191, -0.2759],
        [ 1.3750,  1.5244, -1.7888],
        [ 1.8031, -1.9382, -0.1884],
        [-1.3274, -1.2239,  0.5120],
        [-0.1189,  0.1091,  0.9514],
        [ 0.5034,  1.0998,  1.5295],
        [ 0.0913, -1.4186, -0.0411],
        [ 0.2344, -1.5654, -0.5695],
        [-2.0528, -0.5885,  0.3352],
        [-0.1680,  0.0295,  0.8872],
        [-0.2740, -0.5776,  0.0146],
        [-1.3369, -0.4924,  0.1844],
        [-0.3204, -1.3311,  1.0760],
        [ 0.2851,  1.0180,  0.9794],
        [-1.1371,  0.6101, -0.5773],
        [-1.1510, -0.2933,  0.4069],
        [ 0.2091,  0.4675, -0.5888],
        [-0.5780,  0.5260, -0.0510],
        [ 1.3215, -0.2704, -0.1951],
        [ 0.4039, -0.3133, -0.7963],
        [-0.9440, -0.0809,  0.0392],
        [ 0.5592

In [4]:
dataset[0].forces

tensor([[-1.4186e+00, -7.2142e-01, -8.2763e-01],
        [-1.1633e-01, -1.9197e+00,  1.0299e+00],
        [ 1.2465e+00, -1.5985e+00, -1.4024e+00],
        [ 1.2226e+00, -2.6262e-01, -8.0806e-03],
        [ 2.4437e+00,  6.8134e-01, -3.1273e-01],
        [-1.4379e+00, -1.4291e-02,  5.7725e-01],
        [ 2.3315e+00, -2.5933e-01,  4.6491e-01],
        [-3.4820e+00,  4.4568e+00, -1.1274e+01],
        [-1.8629e+00, -1.0131e-01, -6.8300e-01],
        [-9.5960e-01, -5.1208e-01, -9.1497e-01],
        [-3.2814e+00, -1.5809e+00,  3.0908e+00],
        [ 2.6168e+00, -3.3857e+00, -2.3260e+00],
        [ 2.4991e+00,  2.9580e+00,  2.3120e+00],
        [ 2.5357e-01, -2.2161e-01, -2.5444e+00],
        [-1.6051e+00, -2.1053e+00,  1.7728e+00],
        [-3.0454e-01,  1.6183e-01, -1.3132e+00],
        [-3.8556e-01, -4.3667e-01, -8.1668e-01],
        [ 7.4885e-01,  2.8581e+00,  1.5823e+00],
        [-4.2495e-01, -4.0802e-01, -2.4736e+00],
        [ 2.7168e-01, -2.5362e-01,  2.3107e-01],
        [-8.1415e-01

In [15]:
dataset.get_atoms(0).info

{'source': 'orbnet_denali/orbnet_small_sil_01917_32a8ee422409aa77d5e88000b5dbe379e945715cb7d36030d139db5536749642_309321_0_1/orca.tar.zst',
 'reference_source': None,
 'data_id': 'orbnet_denali',
 'charge': 0,
 'spin': 1,
 'num_atoms': 12,
 'num_electrons': 70,
 'num_ecp_electrons': 0,
 'n_scf_steps': 16,
 'n_basis': 325,
 'unrestricted': False,
 'nl_energy': 7.659100432390547,
 'integrated_densities': array([35.00000775, 35.00000775, 70.00001551]),
 'homo_energy': array([-8.39484865]),
 'homo_lumo_gap': array([7.77845633]),
 's_squared': 0.0,
 's_squared_dev': 0.0,
 'warnings': ['B97M-V or wB97M-V functional requested.libXC variant has now been activated.Any manually given DFX/HFX/RangeSep scaling parameters are IGNORED!',
  'Analytic gradients for DFT-NL dispersion can only be done using the self-consistent method,Switching to SCNL',
  'Self-consistent DFT-NL dispersion not compatible with AutoTRAH.Switching AutoTRAH off'],
 'mulliken_charges': array([-0.601188,  0.402737, -0.306437,

### read in aselmdb

In [8]:
# Source and destination paths
src_path = "/data/ishan-amin/OMOL/val/data0000.aselmdb"
dst_path = "/home/yuejian/project/MLFF-distill/test_dump_aselmdb/copy_0/copy_data0001.aselmdb"

connect_args = {
    "readonly": False,
    "use_lock_file": False,
}

# Open source DB in readonly mode
src_db = ase.db.connect(src_path, **connect_args)
# Open/create destination DB for writing
# dst_db = ase.db.connect(dst_path, use_lock_file=False)

In [18]:
for idx, row in enumerate(tqdm(src_db.select(),total=len(src_db))):
    atoms = row.toatoms()  # Get Atoms object
    print(atoms.calc)
    print(atoms.calc.results.keys())
    print(row.data.keys())
    data = dict(row.data) if hasattr(row, 'data') else {}
    key = getattr(row, 'key', None)
    # print(f"Processing row with key: {key}")
    # Write to the new database, preserving key and metadata
    dst_db.write(atoms, data=data)
    # dst_db.write(atoms, key=key, data=data)
    if idx > 1:
        break

  0%|          | 0/34526 [00:00<?, ?it/s]

SinglePointCalculator(energy=-171993.7618088697, forces=...)
dict_keys(['energy', 'forces'])
dict_keys(['source', 'reference_source', 'data_id', 'charge', 'spin', 'num_atoms', 'num_electrons', 'num_ecp_electrons', 'n_scf_steps', 'n_basis', 'unrestricted', 'nl_energy', 'integrated_densities', 'homo_energy', 'homo_lumo_gap', 's_squared', 's_squared_dev', 'warnings', 'mulliken_charges', 'lowdin_charges', 'composition'])


NameError: name 'dst_db' is not defined

In [7]:
len(src_db)  # Get the number of rows in the source DB

49835

In [8]:
for row in tqdm(src_db.select(),total=len(src_db)):
    atoms = row.toatoms()  # Get Atoms object
    data = dict(row.data) if hasattr(row, 'data') else {}
    key = getattr(row, 'key', None)
    # print(f"Processing row with key: {key}")
    # Write to the new database, preserving key and metadata
    dst_db.write(atoms, data=data)
    # dst_db.write(atoms, key=key, data=data)


  5%|▍         | 2250/49835 [00:03<01:23, 570.21it/s]


KeyboardInterrupt: 

In [9]:
src_db.close()  # Close the source database
dst_db.close()  # Close the destination database

In [6]:
# load dataset
dataset_path = "/home/yuejian/project/MLFF-distill/test_dump_aselmdb/source"
a2g_args = {  
    "molecule_cell_size": 120.0,
    "r_energy": True,
    "r_forces": True,
    # "r_stress": True,
    "r_data_keys": [ 'spin','charge', "data_id"],
    # 'sid': 'data_id',

}
# select_args ={ "data_id":"ani2x"}
# select_args ={"selection": [("charge", "=", -1)] }
select_args = {
    "filter": lambda row: row._data.get("data_id") == "orbnet_denali"
}
source_dataset = AseDBDataset({
                        "src": dataset_path,
                        "a2g_args": a2g_args,
                        # "select_args": select_args,
                        })

In [7]:
# load dataset
dataset_path = "/home/yuejian/project/MLFF-distill/test_dump_aselmdb/copy"
a2g_args = {  
    "molecule_cell_size": 120.0,
    "r_energy": True,
    "r_forces": True,
    # "r_stress": True,
    "r_data_keys": [ 'spin','charge', "data_id"],
    # 'sid': 'data_id',

}
# select_args ={ "data_id":"ani2x"}
# select_args ={"selection": [("charge", "=", -1)] }
select_args = {
    "filter": lambda row: row._data.get("data_id") == "orbnet_denali"
}
copy_dataset = AseDBDataset({
                        "src": dataset_path,
                        "a2g_args": a2g_args,
                        # "select_args": select_args,
                        })

In [27]:
for source,copy in tqdm(zip(source_dataset, copy_dataset), total=len(source_dataset)):
    # check if each argument matches between source and copy
    # AtomicData(atomic_numbers=[14], batch=[14], cell=[1, 3, 3], cell_offsets=[0, 3], charge=[1], data_id=[1], edge_index=[2, 0], energy=[1], fixed=[14], forces=[14, 3], natoms=[1], nedges=[1], pbc=[1, 3], pos=[14, 3], sid=[1], source=[1], spin=[1], tags=[14])
    for key in source.keys():
        if key not in copy.keys():
            print(f"Key {key} not found in copy dataset")
            continue
        if isinstance(source[key], torch.Tensor):
            if not torch.equal(source[key], copy[key]):
                print(f"Mismatch in tensor for key {key}")
        elif isinstance(source[key], np.ndarray):
            if not np.array_equal(source[key], copy[key]):
                print(f"Mismatch in array for key {key}")
        else:
            if source[key] != copy[key]:
                print(f"Mismatch in value for key {key}: {source[key]} != {copy[key]}")
    

100%|██████████| 49835/49835 [01:10<00:00, 707.43it/s]


In [20]:
copy.keys()

{'atomic_numbers',
 'batch',
 'cell',
 'cell_offsets',
 'charge',
 'data_id',
 'edge_index',
 'energy',
 'fixed',
 'forces',
 'natoms',
 'nedges',
 'pbc',
 'pos',
 'sid',
 'source',
 'spin',
 'tags'}

In [14]:
source

AtomicData(atomic_numbers=[14], batch=[14], cell=[1, 3, 3], cell_offsets=[0, 3], charge=[1], data_id=[1], edge_index=[2, 0], energy=[1], fixed=[14], forces=[14, 3], natoms=[1], nedges=[1], pbc=[1, 3], pos=[14, 3], sid=[1], source=[1], spin=[1], tags=[14])

In [11]:
source.source

['ani1xbb/aniBB_014_569966_0_1/orca.tar.zst']

In [26]:
source_dataset[5].pos[:10,:], copy_dataset[5].pos[:10,:]

(tensor([[128.2628, 138.1711, 127.4267],
         [127.7452, 137.1824, 126.3279],
         [127.7188, 137.6234, 125.1517],
         [127.5193, 138.2895, 128.2149],
         [129.2468, 137.9889, 127.8587],
         [128.3287, 139.1104, 126.8776],
         [127.5184, 135.9038, 126.6964],
         [126.8101, 134.9888, 125.8729],
         [125.5702, 134.3704, 126.4981],
         [125.6232, 133.7381, 127.5706]]),
 tensor([[128.2628, 138.1711, 127.4267],
         [127.7452, 137.1824, 126.3279],
         [127.7188, 137.6234, 125.1517],
         [127.5193, 138.2895, 128.2149],
         [129.2468, 137.9889, 127.8587],
         [128.3287, 139.1104, 126.8776],
         [127.5184, 135.9038, 126.6964],
         [126.8101, 134.9888, 125.8729],
         [125.5702, 134.3704, 126.4981],
         [125.6232, 133.7381, 127.5706]]))